return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,
		config = function()
			require("catppuccin").setup({
				flavour = "frappe", -- latte, frappe, macchiato, mocha
				background = {
					-- :h background
					light = "latte",
					dark = "mocha",
				},
				transparent_background = false,
				show_end_of_buffer = false, -- show the '~' characters after the end of buffers
				term_colors = false,
				dim_inactive = {
					enabled = false,
					shade = "dark",
					percentage = 0.15,
				},
				no_italic = false, -- Force no italic
				no_bold = false, -- Force no bold
				no_underline = false, -- Force no underline
				styles = {
					comments = { "italic" },
					conditionals = {},
					loops = {},
					functions = {},
					keywords = { "italic" },
					strings = { "italic" },
					variables = {},
					numbers = {},
					booleans = { "italic" },
					properties = {},
					types = { "bold" },
					operators = {},
				},
				color_overrides = {},
				custom_highlights = function(C)
					return {
						CmpItemKindSnippet = { fg = C.base, bg = C.mauve },
						CmpItemKindKeyword = { fg = C.base, bg = C.red },
						CmpItemKindText = { fg = C.base, bg = C.teal },
						CmpItemKindMethod = { fg = C.base, bg = C.blue },
						CmpItemKindConstructor = { fg = C.base, bg = C.blue },
						CmpItemKindFunction = { fg = C.base, bg = C.blue },
						CmpItemKindFolder = { fg = C.base, bg = C.blue },
						CmpItemKindModule = { fg = C.base, bg = C.blue },
						CmpItemKindConstant = { fg = C.base, bg = C.peach },
						CmpItemKindField = { fg = C.base, bg = C.green },
						CmpItemKindProperty = { fg = C.base, bg = C.green },
						CmpItemKindEnum = { fg = C.base, bg = C.green },
						CmpItemKindUnit = { fg = C.base, bg = C.green },
						CmpItemKindClass = { fg = C.base, bg = C.yellow },
						CmpItemKindVariable = { fg = C.base, bg = C.flamingo },
						CmpItemKindFile = { fg = C.base, bg = C.blue },
						CmpItemKindInterface = { fg = C.base, bg = C.yellow },
						CmpItemKindColor = { fg = C.base, bg = C.red },
						CmpItemKindReference = { fg = C.base, bg = C.red },
						CmpItemKindEnumMember = { fg = C.base, bg = C.red },
						CmpItemKindStruct = { fg = C.base, bg = C.blue },
						CmpItemKindValue = { fg = C.base, bg = C.peach },
						CmpItemKindEvent = { fg = C.base, bg = C.blue },
						CmpItemKindOperator = { fg = C.base, bg = C.blue },
						CmpItemKindTypeParameter = { fg = C.base, bg = C.blue },
						CmpItemKindCopilot = { fg = C.base, bg = C.teal },
					}
				end,
				integrations = {
					aerial = true,
					barbar = false,
					beacon = false,
					cmp = true,
					coc_nvim = false,
					dashboard = false,
					fern = false,
					fidget = true,
					gitgutter = false,
					gitsigns = true,
					harpoon = false,
					headlines = false,
					hop = false,
					illuminate = true,
					leap = false,
					lightspeed = false,
					lsp_saga = true,
					lsp_trouble = false,
					markdown = true,
					mason = true,
					mini = false,
					neogit = false,
					neotest = false,
					neotree = false,
					noice = false,
					notify = true,
					nvimtree = true,
					octo = false,
					overseer = false,
					pounce = false,
					sandwich = false,
					semantic_tokens = false,
					symbols_outline = false,
					telekasten = false,
					telescope = true,
					treesitter = true,
					treesitter_context = false,
					ts_rainbow = false,
					ts_rainbow2 = false,
					vim_sneak = false,
					vimwiki = true,
					which_key = true,
					barbecue = {
						dim_dirname = true,
						bold_basename = true,
						dim_context = false,
						alt_background = false,
					},
					dap = {
						enabled = true,
						enable_ui = true,
					},
					indent_blankline = {
						enabled = true,
						scope_color = "",
						colored_indent_levels = true,
					},
					native_lsp = {
						enabled = true,
						virtual_text = {
							errors = { "italic" },
							hints = { "italic" },
							warnings = { "italic" },
							information = { "italic" },
						},
						underlines = {
							errors = { "underline" },
							hints = { "underline" },
							warnings = { "underline" },
							information = { "underline" },
						},
						inlay_hints = {
							background = true,
						},
					},
					navic = {
						enabled = false,
						custom_bg = "NONE",
					},
					bufferline = true,
				},
			})

			vim.cmd([[colorscheme catppuccin]])
		end,
	},
}
